// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC25JC8vGZ57d09FUlO5o_dXKKrgnRI5iY',
    appId: '1:715758020573:web:8e489a51d8cbdcbea23834',
    messagingSenderId: '715758020573',
    projectId: 'rekach-545b5',
    authDomain: 'rekach-545b5.firebaseapp.com',
    storageBucket: 'rekach-545b5.appspot.com',
    measurementId: 'G-2LQ2GE65TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB87DTeHgA1U0ZYdFRemrGjhDXUTk696GI',
    appId: '1:715758020573:android:9ce894920bd747f8a23834',
    messagingSenderId: '715758020573',
    projectId: 'rekach-545b5',
    storageBucket: 'rekach-545b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKQARcVcsRSJYRgeJT7wr75Lizwj6aX_E',
    appId: '1:715758020573:ios:8b2b828f3d87fd79a23834',
    messagingSenderId: '715758020573',
    projectId: 'rekach-545b5',
    storageBucket: 'rekach-545b5.appspot.com',
    iosClientId: '715758020573-4lkde36lfncrf6gps0s49suqes5ggtqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKQARcVcsRSJYRgeJT7wr75Lizwj6aX_E',
    appId: '1:715758020573:ios:8b2b828f3d87fd79a23834',
    messagingSenderId: '715758020573',
    projectId: 'rekach-545b5',
    storageBucket: 'rekach-545b5.appspot.com',
    iosClientId: '715758020573-4lkde36lfncrf6gps0s49suqes5ggtqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWork',
  );
}
